"""Trace _find_similar_incidents for a T1.1 eval signal."""
import sys
sys.path.insert(0, '.')
sys.path.insert(0, 'Anvil-P-E/bench-p02-context')

from persistent_context_engine import Engine, EngineConfig
from generator import GenConfig, generate

cfg = GenConfig(seed=777, n_services=30, days=14, deploys=80,
                topology_mutations=25, incidents_train=60,
                incidents_eval=20, incident_families=20,
                background_density=100)
ds = generate(cfg)

engine = Engine(EngineConfig(db_path=":memory:", buffer_size=1000))
engine.ingest(ds.train_events)
engine.ingest(ds.eval_events)

sig = ds.eval_signals[1]  # INC-51459-14
signal = {
    "incident_id": sig["incident_id"],
    "ts": sig["ts"],
    "trigger": sig.get("trigger", ""),
    "service": sig.get("service", ""),
}

# What service does this signal resolve to?
svc = signal["service"]
node_id = engine._node_store.resolve(svc)
print(f"service={svc}  node_id={node_id}")

# What does _resolve_all_node_ids return?
all_ids = set(engine._resolve_all_node_ids(node_id)) if node_id else set()
print(f"all alias node_ids ({len(all_ids)}): {list(all_ids)[:5]}")

# What does the pattern table contain for this trigger?
cur = engine._pattern_store._cursor()
total_patterns = cur.execute("SELECT COUNT(*) FROM incident_patterns").fetchone()[0]
print(f"\nTotal patterns in DB: {total_patterns}")

# The query used by _find_similar_incidents
all_rows = cur.execute(
    """SELECT p.incident_id, p.trigger_node_id, p.family_id,
              p.fingerprint_hash, p.fingerprint_tuple, p.created_at
       FROM incident_patterns p
       ORDER BY p.created_at DESC"""
).fetchall()
print(f"Rows returned by pattern query: {len(all_rows)}")

# Are eval signal patterns in the DB?
eval_row = cur.execute(
    "SELECT incident_id, trigger_node_id, fingerprint_hash FROM incident_patterns WHERE incident_id = ?",
    [sig["incident_id"]]
).fetchone()
print(f"\nEval signal in patterns table: {eval_row}")

# How many raw events exist in the buffer window for this signal?
from datetime import datetime, timezone
ts = datetime.fromisoformat(sig["ts"].replace("Z", "+00:00"))
print(f"\nSignal ts: {ts}")

# Check buffer for this service
buf_events = engine._buffer.for_service(svc) if hasattr(engine._buffer, 'for_service') else []
print(f"Buffer events for {svc}: {len(buf_events)}")

# Check how many events are in the window
window_start = ts - engine._fingerprinter.window_before
window_end = ts + engine._fingerprinter.window_after
buf_all = engine._buffer.in_window(window_start, window_end) if hasattr(engine._buffer, 'in_window') else []
print(f"Buffer events in full window: {len(buf_all)}")

# Reconstruct and show full context
ctx = engine.reconstruct_context(signal, mode="fast")
print(f"\nsimilar_incidents: {ctx.get('similar_incidents', [])}")
print(f"causal_chain: {len(ctx.get('causal_chain', []))} items")
print(f"context events: {len(ctx.get('events', []))} items")

# What does _find_similar_incidents get as candidates before filtering?
# Check if the issue is in _resolve_all_node_ids or in _compute_pattern_similarity
if node_id:
    all_ids_list = list(engine._resolve_all_node_ids(node_id))
    print(f"\n_resolve_all_node_ids returned: {all_ids_list}")
    # Check if any pattern has a trigger matching these
    placeholders = ','.join(['?' for _ in all_ids_list])
    if all_ids_list:
        same_trig = cur.execute(
            f"SELECT COUNT(*) FROM incident_patterns WHERE trigger_node_id IN ({placeholders})",
            all_ids_list
        ).fetchone()[0]
        print(f"Patterns with same trigger_node_id: {same_trig}")

# Check what _compute_pattern_similarity returns for the first row
if all_rows:
    inc_id, trig_id, fam_id, fp_hash, fp_tuple, created_at = all_rows[0]
    # Need an IncidentFingerprint object for the current signal
    # Check if fingerprint was even generated by looking at what reconstruct_context does
    print(f"\nFirst stored pattern: inc={inc_id} hash={fp_hash[:16]}...")
    print(f"Checking _compute_pattern_similarity with a dummy current fp hash={fp_hash[:16]}...")
    # If we pass the same hash it should return 1.0
    from persistent_context_engine.incident_fingerprinter import IncidentFingerprint
    import json
    elements = json.loads(fp_tuple)
    dummy_fp = IncidentFingerprint(
        elements=elements, structural_hash=fp_hash,
        trigger_node_id=trig_id, window_start=ts, window_end=ts, event_count=len(elements)
    )
    sim = engine._compute_pattern_similarity(dummy_fp, fp_hash, fp_tuple)
    print(f"Self-similarity (should be 1.0): {sim}")

engine.close()
